[package]
name = "sourcepawn_lsp"
version = "0.9.4"
edition = "2021"
description = "Language Server implemention for the SourcePawn programming language."
license = "GPL-3.0"
exclude = [".gitattributes", ".gitignore", ".github/**", ".vscode/**", "*.snap"]

[[bin]]
name = "sourcepawn_lsp"
test = false

[lib]
doctest = false


[dependencies]
clap = "4.0.26"
lsp-server = "0.6.0"
lsp-types = "0.93.2"
serde = "1.0.147"
serde_json = "^1.0.83"
derive-new = "0.5"
tree-sitter = "0.20.9"
tree-sitter-sourcepawn = "0.5.0"
anyhow = "1.0.66"
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
threadpool = "1.8.1"
walkdir = "2.3.2"
log = "0.4.17"
rowan = "0.15.10"
lazy_static = "1.4.0"
regex = "1.7.0"
notify = "5.1.0"
fxhash = "0.2.1"
tempfile = "3.4.0"

[dependencies.uuid]
version = "1.3.0"
features = ["v4"]

[dev-dependencies]
assert_unordered = "0.3.5"
criterion = { version = "0.4.0" }
insta = { version = "1.28.0", features = ["glob", "redactions", "json"] }

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
