[package]
name = "sourcepawn-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.26"
lsp-server = "0.6.0"
lsp-types = "0.93.2"
serde = "1.0.147"
serde_json = "^1.0.83"
derive-new = "0.5"
tree-sitter = "0.20.9"
tree-sitter-sourcepawn = "0.5.0"
anyhow = "1.0.66"
crossbeam-channel = "0.5.6"
dashmap = "5.4.0"
threadpool = "1.8.1"
