name: release

on:
    release:
        types: [created]

jobs:
    release:
        name: release ${{ matrix.target }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      program: cargo
                      archive: zip

                    - os: windows-latest
                      target: i686-pc-windows-msvc
                      program: cargo
                      archive: zip

                    - os: windows-latest
                      target: aarch64-pc-windows-msvc
                      program: cargo
                      archive: zip

                    - os: macos-latest
                      target: x86_64-apple-darwin
                      program: cargo
                      archive: zip

                    - os: macos-latest
                      target: aarch64-apple-darwin
                      program: cargo
                      archive: zip

                    - os: ubuntu-20.04
                      target: x86_64-unknown-linux-gnu
                      program: cargo
                      archive: zip

                    - os: ubuntu-20.04
                      target: aarch64-unknown-linux-gnu
                      program: cross
                      archive: zip

                    - os: ubuntu-20.04
                      target: armv7-unknown-linux-gnueabihf
                      program: cross
                      archive: zip

                    - os: ubuntu-20.04
                      target: x86_64-unknown-linux-musl
                      program: cargo
                      archive: zip

        steps:
            - uses: actions/checkout@master
            - name: Compile and release
              uses: rust-build/rust-build.action@v1.3.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  RUSTTARGET: ${{ matrix.target }}
                  ARCHIVE_TYPES: ${{ matrix.archive }}
            - name: Add changelog
              id: changelog
              uses: mindsers/changelog-reader-action@v2.0.0
            - name: Edit Release
              uses: irongut/EditRelease@v1.2.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  id: ${{ github.event.release.id }}
                  body: ${{ steps.changelog.outputs.changes }}
                  replacebody: true

    cargo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true
            - uses: katyo/publish-crates@v1
              with:
                  registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
                  args: --allow-dirty
